<a href="https://colab.research.google.com/github/KrizHa/ML_task/blob/main/HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

#Стврорення вектора
vector = np.random.rand(10)


# Створення матриці
matrix = np.array([[11,14, 17],
                   [20, 23, 26],
                   [29, 32, 35]])

print("Вектор:")
print(vector)
print("\nМатриця:")
print(matrix)

vector_shape = vector.shape
matrix_shape = matrix.shape

print("\nРозмірність вектора:", vector_shape)
print("Розмірність матриці:", matrix_shape)

Вектор:
[0.69713467 0.69318468 0.36311638 0.93183063 0.38341746 0.82681615
 0.3408625  0.27392887 0.97830622 0.40371377]

Матриця:
[[11 14 17]
 [20 23 26]
 [29 32 35]]

Розмірність вектора: (10,)
Розмірність матриці: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [2]:
vector_10 = np.round(vector + 10, 2)
matrix_2 = matrix * 2
vector_square = np.square(vector)

vector_10, matrix_2, vector_square

(array([10.7 , 10.69, 10.36, 10.93, 10.38, 10.83, 10.34, 10.27, 10.98,
        10.4 ]),
 array([[22, 28, 34],
        [40, 46, 52],
        [58, 64, 70]]),
 array([0.48599675, 0.480505  , 0.13185351, 0.86830832, 0.14700895,
        0.68362494, 0.11618724, 0.07503702, 0.95708307, 0.16298481]))


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [3]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [4]:
result_matrix = np.dot(B, A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [5]:
result_matrix_C = np.dot(result_matrix, C)
result_matrix_C

array([[0.5202],
       [0.2846]])

In [6]:
result_matrix_D = np.dot(result_matrix, D)
result_matrix_D

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [7]:
# Транспонування
result_matrix_T = result_matrix.T
result_matrix_T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [8]:
vector_T = vector.T
vector_T, vector_T.shape

(array([0.69713467, 0.69318468, 0.36311638, 0.93183063, 0.38341746,
        0.82681615, 0.3408625 , 0.27392887, 0.97830622, 0.40371377]),
 (10,))

In [9]:
column_vector = np.expand_dims(vector, axis=1)
column_vector, column_vector.shape

(array([[0.69713467],
        [0.69318468],
        [0.36311638],
        [0.93183063],
        [0.38341746],
        [0.82681615],
        [0.3408625 ],
        [0.27392887],
        [0.97830622],
        [0.40371377]]),
 (10, 1))

In [10]:
column_vector_T = column_vector.T
column_vector_T, column_vector_T.shape


(array([[0.69713467, 0.69318468, 0.36311638, 0.93183063, 0.38341746,
         0.82681615, 0.3408625 , 0.27392887, 0.97830622, 0.40371377]]),
 (1, 10))